import "./globals.scss";
import AuthProvider from "@/context/AuthContext";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Plants Box",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <main className="flex-1 flex items-center justify-center">
          <AuthProvider>{children}</AuthProvider>
        </main>
        <Footer />
      </body>
    </html>
  );
}
